### ISSUE TITLE
graphiql interface does not load

### ISSUE THREAD

**Issue by rdsteiner** [jjn1056/Plack-App-GraphQL#2]
Loading the GraphiQL interface does not work with the current "latest" minified version of graphiql.min.js.

Error:
Cannot use e "__Schema" from another module or realm.

Works with:
- unminified 'latest' version
- minified '0.14.2' version

I'll provide a pull request with one workaround.

**Comment by jjn1056** [comment]
weird that the unminified latest works, seems like an error in the compaction process.  Is there a ticket open on that?

In any case your patch is useful and merged.  I'm closing this and cutting a new release in a bit
